version: "3.8"
services:
  bot-db:
    image: mongo:latest
    container_name: bot-db
    restart: unless-stopped
    command: mongod
    environment:
      MONGO_INITDB_DATABASE: coinpay-bot-db
      MONGODB_DATA_DIR: /data/db
      MONDODB_LOG_DIR: /dev/null
    volumes:
      - mongodbdata:/data/db
    ports:
      - 27017:27017
  bot:
    image: coinpay-tracker
    container_name: bot
    environment:
      API_ENDPOINT: https://coinpay.org.ua/api/v1
      BOT_TOKEN: "${BOT_API_TOKEN}"
      DB_NAME: coinpay-bot-db
      DB_HOST: bot-db
    depends_on:
      - bot-db
volumes:
  mongodbdata: